<?php
	//include all DAO files
	require_once('class/sql/Connection.class.php');
	require_once('class/sql/ConnectionFactory.class.php');
	require_once('class/sql/ConnectionProperty.class.php');
	require_once('class/sql/QueryExecutor.class.php');
	require_once('class/sql/Transaction.class.php');
	require_once('class/sql/SqlQuery.class.php');
	require_once('class/core/ArrayList.class.php');
	require_once('class/dao/DAOFactory.class.php');
 	
	require_once('class/dao/CommandDAO.class.php');
	require_once('class/dto/Command.class.php');
	require_once('class/mysql/CommandMySqlDAO.class.php');
	require_once('class/mysql/ext/CommandMySqlExtDAO.class.php');
	require_once('class/dao/EnterpriseDAO.class.php');
	require_once('class/dto/Enterprise.class.php');
	require_once('class/mysql/EnterpriseMySqlDAO.class.php');
	require_once('class/mysql/ext/EnterpriseMySqlExtDAO.class.php');
	require_once('class/dao/TerminalDAO.class.php');
	require_once('class/dto/Terminal.class.php');
	require_once('class/mysql/TerminalMySqlDAO.class.php');
	require_once('class/mysql/ext/TerminalMySqlExtDAO.class.php');
	require_once('class/dao/TerminalgroupDAO.class.php');
	require_once('class/dto/Terminalgroup.class.php');
	require_once('class/mysql/TerminalgroupMySqlDAO.class.php');
	require_once('class/mysql/ext/TerminalgroupMySqlExtDAO.class.php');
	require_once('class/dao/TerminalstatusDAO.class.php');
	require_once('class/dto/Terminalstatu.class.php');
	require_once('class/mysql/TerminalstatusMySqlDAO.class.php');
	require_once('class/mysql/ext/TerminalstatusMySqlExtDAO.class.php');
	require_once('class/dao/UserDAO.class.php');
	require_once('class/dto/User.class.php');
	require_once('class/mysql/UserMySqlDAO.class.php');
	require_once('class/mysql/ext/UserMySqlExtDAO.class.php');
	require_once('class/dao/UserTgroupDAO.class.php');
	require_once('class/dto/UserTgroup.class.php');
	require_once('class/mysql/UserTgroupMySqlDAO.class.php');
	require_once('class/mysql/ext/UserTgroupMySqlExtDAO.class.php');

?>